# Generated by Django 5.0.3 on 2025-01-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('phno', models.IntegerField()),
                ('resume', models.FileField(upload_to='media/')),
            ],
        ),
    ]
