# Generated by Django 5.0.3 on 2025-01-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
